# Generated by Django 2.2.28 on 2022-12-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addressiipwrtqqnr'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressiipwrtqqnr',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
